## Service
---
apiVersion: v1
kind: Service
metadata:
   name: overseerr
   namespace: mediaserver
   labels:
     app: overseerr
spec:
  clusterIP: None
  ports:
  - port: 5055
  selector:
    app: overseerr




## Volumes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
  namespace: mediaserver
  labels:
    name: overseerr-config
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: longhorn-perpetual
  resources:
    requests:
      storage: 8Gi
